import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getAuth, signInAnonymously, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js";
import { getFirestore, collection, doc, addDoc, setDoc, updateDoc, deleteDoc, onSnapshot, query, orderBy, serverTimestamp, getDoc } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyC68C7zbfhkA2P9QuQqjkqCZRlfK06ZIRw",authDomain:"sartors-central.firebaseapp.com",projectId:"sartors-central",storageBucket:"sartors-central.firebasestorage.app",messagingSenderId:"317751336167",appId:"1:317751336167:web:1108a63aa8473ef84e9642",measurementId:"G-PQN9X7E0NH"};
const MEMBERS={tamara:{name:"Tamara",role:"Mom",color:"#905671"},matt:{name:"Matt",role:"Dad",color:"#41748a"},tommy:{name:"Tommy",role:"Son",color:"#668640"},charlie:{name:"Charlie",role:"Daughter",color:"#a16d39"}};
const ADMINS=["tamara","matt","tommy"], FAMILY="sartors";
const fb=initializeApp(firebaseConfig), auth=getAuth(fb), db=getFirestore(fb);
const app=document.querySelector('#app'), modalRoot=document.querySelector('#modal-root'), toastRoot=document.querySelector('#toast-root');
let uid=null, member=localStorage.getItem('sc-member')||null, page='calendar', calendarView='week', cursor=startOfWeek(new Date()), data={events:[],dinners:new Map(),lists:new Map(),requests:[]}, unsubs=[], busy=new Set();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c]));
const iso=d=>{const x=new Date(d);x.setHours(0,0,0,0);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const parseDate=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const startOfWeek=d=>{const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x};
const plusDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const fmtDay=(d,opts={weekday:'long',month:'long',day:'numeric'})=>new Intl.DateTimeFormat('en-US',opts).format(d);
const timeFmt=t=>{if(!t)return '';const [h,m]=t.split(':').map(Number);const ap=h>=12?'PM':'AM',hh=h%12||12;return `${hh}${m?`:${String(m).padStart(2,'0')}`:''} ${ap}`};
const eventTime=e=>e.startTime?(e.endTime?`${timeFmt(e.startTime)}–${timeFmt(e.endTime).replace(' ','')}`:timeFmt(e.startTime)):'';
const canEdit=()=>ADMINS.includes(member);
function toast(text,type=''){const n=document.createElement('div');n.className=`toast ${type}`;n.textContent=text;toastRoot.append(n);setTimeout(()=>n.remove(),4200)}
function setBusy(k,on){on?busy.add(k):busy.delete(k)}
async function write(k,fn){if(busy.has(k))return;setBusy(k,true);try{await fn()}catch(e){console.error(e);toast(e.code==='permission-denied'?'You do not have permission for that action.':'Could not save your change. Check your connection and try again.','error')}finally{setBusy(k,false)}}
function closeModal(){modalRoot.innerHTML=''}
function modal(title,body,foot=''){modalRoot.innerHTML=`<div class="modal-backdrop" data-close-modal><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><h2 id="modal-title">${esc(title)}</h2><button class="icon-button" data-close-modal aria-label="Close dialog">Close</button></div><div class="modal-body">${body}</div>${foot?`<div class="modal-foot">${foot}</div>`:''}</section></div>`;modalRoot.querySelector('.modal').focus?.()}
modalRoot.addEventListener('click',e=>{if(e.target.matches('[data-close-modal]'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
function dbPath(kind,id){return id?doc(db,'families',FAMILY,kind,id):collection(db,'families',FAMILY,kind)}
function subscribe(){unsubs.forEach(x=>x());unsubs=[];unsubs.push(onSnapshot(query(dbPath('events'),orderBy('date'),orderBy('startTime')),s=>{data.events=s.docs.map(d=>({id:d.id,...d.data()}));render()},err=>fail(err)));unsubs.push(onSnapshot(dbPath('dinners'),s=>{data.dinners=new Map(s.docs.map(d=>[d.id,{id:d.id,...d.data()}]));render()},err=>fail(err)));unsubs.push(onSnapshot(dbPath('lists'),s=>{data.lists=new Map(s.docs.map(d=>[d.id,{id:d.id,...d.data()}]));render()},err=>fail(err)));unsubs.push(onSnapshot(query(dbPath('requests'),orderBy('createdAt','desc')),s=>{data.requests=s.docs.map(d=>({id:d.id,...d.data()}));render()},err=>fail(err)))}
function fail(e){console.error(e);document.querySelector('.status-banner')?.remove();const b=document.createElement('div');b.className='status-banner';b.innerHTML='<p>Live data could not load. Check Firebase setup, Firestore rules, and your connection.</p>';app.prepend(b)}
async function ensureBase(){await Promise.all(['shopping','todo'].map(id=>setDoc(dbPath('lists',id),{name:id==='shopping'?'Shopping':'To Do',type:id==='shopping'?'shopping':'todo',items:[]},{merge:true})))}
function header(){const m=MEMBERS[member];const nav=[['calendar','Calendar'],['dinner','Dinner'],['lists','Lists'],...(canEdit()?[['dashboard','List Dashboard']]:[])];return `<header class="site-header"><div class="header-inner"><div class="brand">SARTORS CENTRAL</div><nav class="nav" aria-label="Main navigation">${nav.map(([p,n])=>`<button data-page="${p}" class="${page===p?'active':''}" aria-current="${page===p?'page':'false'}">${n}</button>`).join('')}</nav><div class="profile" style="--member:${m.color}"><span class="member-dot"></span><span>${esc(m.name)}</span><button class="button small" data-switch>Switch person</button></div></div></header>`}
function render(){if(!member){renderPicker();return}if(page==='dashboard'&&!canEdit())page='calendar';app.innerHTML=header()+`<main class="page">${page==='calendar'?calendarPage():page==='dinner'?dinnerPage():page==='lists'?listsPage():dashboardPage()}</main>`;bindPage()}
function renderPicker(){app.innerHTML=`<main class="loading"><section class="picker"><div class="brand">SARTORS CENTRAL</div><h1>Who are you?</h1><p style="color:var(--muted);margin:0">Choose the person using this device. You can change this any time.</p><div class="picker-options">${Object.entries(MEMBERS).map(([id,m])=>`<button class="person-choice" data-person="${id}"><span class="member-dot" style="--member:${m.color};background:${m.color}"></span>${m.name}<span style="margin-left:auto;color:var(--muted);font-weight:500">${m.role}</span></button>`).join('')}</div></section></main>`;document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>selectMember(b.dataset.person))}
async function selectMember(id){member=id;localStorage.setItem('sc-member',id);await write('member',async()=>{await setDoc(doc(db,'families',FAMILY,'members',id,'devices',uid),{uid,member:id,lastSeen:serverTimestamp()},{merge:true});await setDoc(doc(db,'families',FAMILY,'members',id),{name:MEMBERS[id].name,role:MEMBERS[id].role,updatedAt:serverTimestamp()},{merge:true});await ensureBase()});subscribe();render()}
function calendarPage(){const isWeek=calendarView==='week',start=isWeek?startOfWeek(cursor):new Date(cursor.getFullYear(),cursor.getMonth(),1),label=isWeek?`${fmtDay(start,{month:'short',day:'numeric'})} – ${fmtDay(plusDays(start,6),{month:'short',day:'numeric',year:'numeric'})}`:new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(start);return `<div class="page-head"><div><h1>Calendar</h1><p>${label}</p></div><div class="toolbar"><button class="button" data-cal-nav="prev">Previous</button><button class="button" data-cal-today>Today</button><button class="button" data-cal-nav="next">Next</button><div class="segmented"><button data-cal-view="week" class="${isWeek?'active':''}">Week</button><button data-cal-view="month" class="${!isWeek?'active':''}">Month</button></div>${canEdit()?'<button class="button primary" data-new-event>New event</button>':''}</div></div><section class="calendar-shell">${isWeek?weekGrid(start):monthGrid(start)}</section><div class="legend"><span><i style="--c:var(--tamara)"></i>Tamara</span><span><i style="--c:var(--matt)"></i>Matt</span><span><i style="--c:var(--tommy)"></i>Tommy</span><span><i style="--c:var(--charlie)"></i>Charlie</span><span><i style="--c:#99a6aa"></i>Multiple people</span><span><i style="--c:var(--dinner)"></i>Dinner</span></div>`}
function dayItems(d,compact=false){const id=iso(d), ev=data.events.filter(e=>e.date===id), dinner=data.dinners.get(id), all=[...ev.map(e=>({type:'event',v:e})),...(dinner?.meal?[{type:'dinner',v:dinner}]:[])];return all.map(x=>x.type==='dinner'?`<button class="event-chip dinner" data-dinner="${id}" title="Dinner: ${esc(x.v.meal)}"><span>${esc(x.v.meal)}</span></button>`:`<button class="event-chip ${x.v.members?.length>1?'multiple':''}" style="--event-color:${eventColor(x.v)};--event-bg:${eventBg(x.v)}" data-event="${x.v.id}"><span>${esc(x.v.name)}</span>${compact?'':x.v.startTime?`<span class="chip-time">${esc(eventTime(x.v))}</span>`:''}</button>`).join('')}
function weekGrid(start){return `<div class="week-grid">${Array.from({length:7},(_,i)=>{const d=plusDays(start,i),today=iso(d)===iso(new Date());return `<article class="cal-day ${today?'is-today mobile-show':''}"><div class="day-header"><span class="dow">${fmtDay(d,{weekday:'short'})}</span><span class="date-num">${d.getDate()}</span></div>${dayItems(d)||'<div class="cal-empty">No events scheduled</div>'}</article>`}).join('')}</div>`}
function monthGrid(start){const first=startOfWeek(start), days=Array.from({length:42},(_,i)=>plusDays(first,i));return `<div class="month-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="month-weekday">${x}</div>`).join('')}${days.map(d=>`<article class="month-day ${d.getMonth()!==start.getMonth()?'muted':''} ${iso(d)===iso(new Date())?'is-today':''}"><div class="month-date">${d.getDate()}</div>${dayItems(d,true)}</article>`).join('')}</div>`}
function eventColor(e){if((e.members||[]).length!==1)return '#99a6aa';return MEMBERS[e.members[0]]?.color||'#99a6aa'}function eventBg(e){if((e.members||[]).length!==1)return '#f8faf9';const c=eventColor(e);return c+'1c'}
function dinnerPage(){const start=startOfWeek(cursor);return `<div class="page-head"><div><h1>Dinner planner</h1><p>Click any day to set or change the meal.</p></div><div class="toolbar"><button class="button" data-dinner-nav="prev">Previous week</button><button class="button" data-dinner-today>This week</button><button class="button" data-dinner-nav="next">Next week</button></div></div><section class="meal-week">${Array.from({length:7},(_,i)=>{const d=plusDays(start,i),meal=data.dinners.get(iso(d))?.meal||'';return `<article class="meal-day ${iso(d)===iso(new Date())?'today':''}"><h2>${fmtDay(d,{weekday:'long'})}</h2><button class="meal-edit ${meal?'':'empty'}" data-dinner="${iso(d)}">${meal?esc(meal):'Dinner not planned'}</button></article>`}).join('')}</section>`}
function listDoc(id){return data.lists.get(id)||{id,name:id==='shopping'?'Shopping':'To Do',items:[]}}
function sortedItems(items=[]){return [...items].sort((a,b)=>Number(!!a.done)-Number(!!b.done)||String(a.createdAt||'').localeCompare(String(b.createdAt||'')))}
function itemsMarkup(list,{manage=false}={}){const it=sortedItems(list.items);if(!it.length)return `<div class="empty">${list.type==='shopping'?'Shopping list is empty':list.type==='todo'?'Nothing to do':'This list is empty'}</div>`;return it.map(x=>`<div class="item-row"><input type="checkbox" ${x.done?'checked':''} ${canEdit()?'':'disabled'} data-toggle-item="${list.id}|${x.id}" aria-label="Mark ${esc(x.text)} complete"><span class="item-text ${x.done?'done':''}">${esc(x.text)}</span>${manage?`<span class="row-actions"><button class="text-btn" data-edit-item="${list.id}|${x.id}">Edit</button><button class="text-btn danger" data-delete-item="${list.id}|${x.id}">Delete</button></span>`:''}</div>`).join('')}
function listsPage(){const lists=[listDoc('shopping'),listDoc('todo'),...Array.from(data.lists.values()).filter(x=>x.type==='temporary').sort((a,b)=>a.name.localeCompare(b.name))];return `<div class="page-head"><div><h1>Lists</h1><p>Your family's active lists in one place.</p></div>${member==='charlie'?'<button class="button primary" data-request>Submit a special request</button>':''}</div><section class="lists-grid">${lists.map(l=>`<article class="list-panel view-list"><h2>${esc(l.name)}</h2>${itemsMarkup(l)}</article>`).join('')}</section>`}
function dashboardPage(){const shopping=listDoc('shopping'),todo=listDoc('todo'),temps=Array.from(data.lists.values()).filter(x=>x.type==='temporary').sort((a,b)=>a.name.localeCompare(b.name));return `<div class="page-head"><div><h1>List Dashboard</h1><p>Manage household lists and special requests.</p></div><button class="button primary" data-new-temp>New temporary list</button></div><section class="dashboard-grid"><article class="list-panel">${manageList(shopping)}</article><article class="list-panel">${manageList(todo)}</article><article class="list-panel wide"><div class="panel-title"><h2>Temporary lists</h2></div>${temps.length?`<div class="lists-grid">${temps.map(l=>`<section class="list-panel" style="padding:14px"><div class="panel-title"><h2>${esc(l.name)}</h2><button class="text-btn danger" data-delete-list="${l.id}">Delete list</button></div>${itemsMarkup(l,{manage:true})}${addItem(l.id)}</section>`).join('')}</div>`:'<div class="empty">No temporary lists yet.</div>'}</article><article class="list-panel wide"><div class="panel-title"><h2>Special requests</h2></div>${data.requests.length?data.requests.map(r=>`<div class="request"><div class="request-meta">${esc(MEMBERS[r.member]?.name||r.member||'Family member')}</div><p>${esc(r.text)}</p><button class="button small" data-request-shop="${r.id}">Add to Shopping</button> <button class="button small" data-request-dismiss="${r.id}">Dismiss</button></div>`).join(''):'<div class="empty">No special requests</div>'}</article></section>`}
function manageList(l){return `<div class="panel-title"><h2>${esc(l.name)}</h2></div>${itemsMarkup(l,{manage:true})}${addItem(l.id)}`};function addItem(id){return `<div class="add-row"><input class="input" data-add-input="${id}" placeholder="Add an item" aria-label="Add item"><button class="button" data-add-item="${id}">Add</button></div>`}
function bindPage(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelector('[data-switch]')?.addEventListener('click',()=>{member=null;localStorage.removeItem('sc-member');render()});document.querySelectorAll('[data-cal-view]').forEach(b=>b.onclick=()=>{calendarView=b.dataset.calView;render()});document.querySelectorAll('[data-cal-nav]').forEach(b=>b.onclick=()=>{cursor=calendarView==='week'?plusDays(cursor,b.dataset.calNav==='next'?7:-7):new Date(cursor.getFullYear(),cursor.getMonth()+(b.dataset.calNav==='next'?1:-1),1);render()});document.querySelector('[data-cal-today]')?.addEventListener('click',()=>{cursor=startOfWeek(new Date());render()});document.querySelector('[data-new-event]')?.addEventListener('click',()=>eventForm());document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>eventDetails(data.events.find(x=>x.id===b.dataset.event)));document.querySelectorAll('[data-dinner]').forEach(b=>b.onclick=()=>dinnerForm(b.dataset.dinner));document.querySelectorAll('[data-dinner-nav]').forEach(b=>b.onclick=()=>{cursor=plusDays(startOfWeek(cursor),b.dataset.dinnerNav==='next'?7:-7);render()});document.querySelector('[data-dinner-today]')?.addEventListener('click',()=>{cursor=startOfWeek(new Date());render()});document.querySelector('[data-request]')?.addEventListener('click',requestForm);document.querySelector('[data-new-temp]')?.addEventListener('click',temporaryForm);document.querySelectorAll('[data-add-item]').forEach(b=>b.onclick=()=>quickAdd(b.dataset.addItem));document.querySelectorAll('[data-add-input]').forEach(i=>i.addEventListener('keydown',e=>{if(e.key==='Enter')quickAdd(i.dataset.addInput)}));document.querySelectorAll('[data-toggle-item]').forEach(c=>c.onchange=()=>toggleItem(c.dataset.toggleItem));document.querySelectorAll('[data-edit-item]').forEach(b=>b.onclick=()=>editItem(b.dataset.editItem));document.querySelectorAll('[data-delete-item]').forEach(b=>b.onclick=()=>deleteItem(b.dataset.deleteItem));document.querySelectorAll('[data-delete-list]').forEach(b=>b.onclick=()=>deleteList(b.dataset.deleteList));document.querySelectorAll('[data-request-shop]').forEach(b=>b.onclick=()=>requestToShopping(b.dataset.requestShop));document.querySelectorAll('[data-request-dismiss]').forEach(b=>b.onclick=()=>dismissRequest(b.dataset.requestDismiss))}
function eventForm(e=null){if(!canEdit())return;const v=e||{date:iso(new Date()),name:'',startTime:'',endTime:'',members:[],where:'',what:'',details:''};modal(e?'Edit event':'New event',`<form id="event-form"><div class="field"><label for="event-name">Event name</label><input class="input" id="event-name" required maxlength="100" value="${esc(v.name)}"></div><div class="form-grid"><div class="field"><label for="event-date">Date</label><input class="input" id="event-date" type="date" required value="${esc(v.date)}"></div><div class="field"><label>Family members</label><div class="member-checks">${Object.entries(MEMBERS).map(([id,m])=>`<label class="member-check"><input type="checkbox" value="${id}" ${(v.members||[]).includes(id)?'checked':''}>${m.name}</label>`).join('')}</div><div class="field-hint">Choose one or more people.</div></div><div class="field"><label for="event-start">Start time</label><input class="input" id="event-start" type="time" value="${esc(v.startTime)}"></div><div class="field"><label for="event-end">End time</label><input class="input" id="event-end" type="time" value="${esc(v.endTime)}"></div></div><div class="field"><label for="event-where">Where</label><input class="input" id="event-where" maxlength="150" value="${esc(v.where)}"></div><div class="field"><label for="event-what">What</label><input class="input" id="event-what" maxlength="150" value="${esc(v.what)}"></div><div class="field"><label for="event-details">Details</label><textarea id="event-details" rows="3" maxlength="1000">${esc(v.details)}</textarea></div></form>`,`<button class="button" data-close-modal>Cancel</button>${e?'<button class="button danger" id="delete-event">Delete</button>':''}<button class="button primary" id="save-event">Save event</button>`);document.querySelector('#save-event').onclick=async()=>{const f=document.querySelector('#event-form');if(!f.reportValidity())return;const start=f.querySelector('#event-start').value,end=f.querySelector('#event-end').value;if(start&&end&&end<=start){toast('End time must be after start time.','error');return}const x={name:f.querySelector('#event-name').value.trim(),date:f.querySelector('#event-date').value,startTime:start,endTime:end,members:[...f.querySelectorAll('input[type=checkbox]:checked')].map(c=>c.value),where:f.querySelector('#event-where').value.trim(),what:f.querySelector('#event-what').value.trim(),details:f.querySelector('#event-details').value.trim(),updatedAt:serverTimestamp(),updatedBy:member};await write('event-save',async()=>{e?await updateDoc(dbPath('events',e.id),x):await addDoc(dbPath('events'),{...x,createdAt:serverTimestamp(),createdBy:member});closeModal()})};document.querySelector('#delete-event')?.addEventListener('click',()=>deleteEvent(e.id)}
function eventDetails(e){if(!e)return;modal(e.name,`<div class="detail"><dl><dt>When</dt><dd>${esc(fmtDay(parseDate(e.date)))}${e.startTime?`, ${esc(eventTime(e))}`:''}</dd><dt>Who</dt><dd>${esc((e.members||[]).map(x=>MEMBERS[x]?.name).filter(Boolean).join(', ')||'Not assigned')}</dd><dt>Where</dt><dd>${esc(e.where||'—')}</dd><dt>What</dt><dd>${esc(e.what||'—')}</dd><dt>Details</dt><dd>${esc(e.details||'—')}</dd></dl></div>`,canEdit()?`<button class="button" data-close-modal>Close</button><button class="button primary" id="edit-event">Edit event</button>`:'<button class="button" data-close-modal>Close</button>');document.querySelector('#edit-event')?.addEventListener('click',()=>eventForm(e))}
async function deleteEvent(id){await write('event-delete',async()=>{await deleteDoc(dbPath('events',id));closeModal()})}
function dinnerForm(date){const cur=data.dinners.get(date)||{}, d=parseDate(date);modal(`Dinner — ${fmtDay(d)}`,`<div class="field"><label for="meal">Meal</label><input class="input" id="meal" maxlength="160" value="${esc(cur.meal||'')}" placeholder="Dinner not planned" autofocus><div class="field-hint">Leave blank to clear the meal. A time is optional.</div></div><div class="field"><label for="meal-time">Time (optional)</label><input class="input" id="meal-time" type="time" value="${esc(cur.time||'')}"></div>`,`<button class="button" data-close-modal>Cancel</button>${canEdit()?'<button class="button primary" id="save-meal">Save dinner</button>':''}`);if(!canEdit())return;document.querySelector('#save-meal').onclick=()=>write('meal-save',async()=>{const meal=document.querySelector('#meal').value.trim(),time=document.querySelector('#meal-time').value;if(meal)await setDoc(dbPath('dinners',date),{date,meal,time,updatedAt:serverTimestamp(),updatedBy:member},{merge:true});else await deleteDoc(dbPath('dinners',date));closeModal()})}
function quickAdd(listId){if(!canEdit())return;const input=document.querySelector(`[data-add-input="${listId}"]`),text=input.value.trim();if(!text)return;const l=listDoc(listId),items=[...(l.items||[]),{id:crypto.randomUUID(),text,done:false,createdAt:new Date().toISOString()}];write(`add-${listId}`,async()=>{await updateDoc(dbPath('lists',listId),{items,updatedAt:serverTimestamp(),updatedBy:member});input.value=''})}
function splitKey(s){return s.split('|')}async function toggleItem(key){if(!canEdit())return;const [lid,iid]=splitKey(key),l=listDoc(lid),items=l.items.map(x=>x.id===iid?{...x,done:!x.done}:x);await write(`toggle-${key}`,()=>updateDoc(dbPath('lists',lid),{items,updatedAt:serverTimestamp(),updatedBy:member}))}
function editItem(key){const[lid,iid]=splitKey(key),item=listDoc(lid).items.find(x=>x.id===iid);modal('Edit item',`<div class="field"><label for="edit-item-text">Item</label><input id="edit-item-text" class="input" value="${esc(item.text)}" maxlength="200"></div>`,`<button class="button" data-close-modal>Cancel</button><button class="button primary" id="save-item">Save</button>`);document.querySelector('#save-item').onclick=()=>{const text=document.querySelector('#edit-item-text').value.trim();if(!text)return;const l=listDoc(lid),items=l.items.map(x=>x.id===iid?{...x,text}:x);write(`edit-${key}`,async()=>{await updateDoc(dbPath('lists',lid),{items,updatedAt:serverTimestamp(),updatedBy:member});closeModal()})}}
async function deleteItem(key){const[lid,iid]=splitKey(key),l=listDoc(lid),items=l.items.filter(x=>x.id!==iid);await write(`del-${key}`,()=>updateDoc(dbPath('lists',lid),{items,updatedAt:serverTimestamp(),updatedBy:member}))}
function temporaryForm(){modal('New temporary list',`<div class="field"><label for="list-name">List name</label><input class="input" id="list-name" maxlength="60" placeholder="For example, Costco"></div>`,`<button class="button" data-close-modal>Cancel</button><button class="button primary" id="save-list">Create list</button>`);document.querySelector('#save-list').onclick=()=>{const name=document.querySelector('#list-name').value.trim();if(!name)return;write('temp-list',async()=>{await addDoc(dbPath('lists'),{name,type:'temporary',items:[],createdAt:serverTimestamp(),createdBy:member});closeModal()})}}
async function deleteList(id){await write(`list-${id}`,()=>deleteDoc(dbPath('lists',id)))}
function requestForm(){modal('Special request',`<div class="field"><label for="request-text">What would you like to request?</label><textarea id="request-text" rows="3" maxlength="300" placeholder="For example, yogurt"></textarea></div>`,`<button class="button" data-close-modal>Cancel</button><button class="button primary" id="save-request">Submit request</button>`);document.querySelector('#save-request').onclick=()=>{const text=document.querySelector('#request-text').value.trim();if(!text)return;write('request',async()=>{await addDoc(dbPath('requests'),{text,member,createdAt:serverTimestamp()});closeModal();toast('Your special request was submitted.')})}}
async function requestToShopping(id){const r=data.requests.find(x=>x.id===id);if(!r)return;const l=listDoc('shopping'),items=[...(l.items||[]),{id:crypto.randomUUID(),text:r.text,done:false,createdAt:new Date().toISOString(),fromRequest:id}];await write(`req-shop-${id}`,async()=>{await updateDoc(dbPath('lists','shopping'),{items,updatedAt:serverTimestamp(),updatedBy:member});await deleteDoc(dbPath('requests',id))})}
async function dismissRequest(id){await write(`req-del-${id}`,()=>deleteDoc(dbPath('requests',id)))}
onAuthStateChanged(auth,u=>{if(u){uid=u.uid;if(member){selectMember(member)}else render()}else signInAnonymously(auth).catch(e=>{console.error(e);app.innerHTML='<main class="loading">Could not start the secure family session. Check Firebase Authentication configuration.</main>'})});
